name: CI Back-end

on:
  push:
    branches:
      - 'main'
    paths:
      - 'back-end/**'
  
jobs:

  teste:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Teste1
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'zulu'
      - name: Teste2
        working-directory: back-end/
        run: mvn --activate-profiles prod test

  cria-arquivo:
    needs: teste
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: CriaJAR1
        uses: actions/setup-java@v3
        with: 
          java-version: '11'
          distribution: 'zulu'
      - name: CriaJAR2
        working-directory: back-end/
        run: vn --activate-profiles prod -DskipTests package
    

  
