name: CI Back-end Merge Branches 

on:
  push:
    branches:
      - '**'
      - '!main'
    paths:
      - 'back/end/**'
  
jobs:

  main:
    name: CI Workflow Main 
    uses: ./.github/workflow/ci-backend-main.yml

  merge:
    needs: main
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Merge branch
        uses: devvmasx/merge-branch@1.4.0
        with:
          type: now
          target_branch: main
          github_token: ${{ github.token }}